### ISSUE TITLE
Fix naming scheme for de novo OTUs

### ISSUE THREAD

**Issue by mooreryan** [mooreryan/ZetaHunter#20]
Make it look more like the Zeta OTUs maybe.

**Comment by mooreryan** [comment]
How did you want to name de novo OTUs @seanmcallister?

**Comment by seanmcallister** [comment]
ZOTUs are for the ones that are in the curated database. User generated de novo OTUs should be something like "NZOTU" for novel or new ZOTUs. Or "ZOTU N1" etc.

**Comment by mooreryan** [comment]
OTU matching database: `ZetaOtu3`
New ZetaOtu: `NewZetaOtu3`

Completed with commit 36508a34b05aa3251ee695a9f0e9bf4f3b062ef6.
