### ISSUE TITLE
Cytoscape output redundancies

### ISSUE THREAD

**Issue by seanmcallister** [mooreryan/ZetaHunter#27]
Cytoscape output does not need to have rows where node1 and node2 are the same OTU, **unless there is only one ZetaOTU found within a sample**. So if there are more than one ZOTU in a sample, then there is no need for the self-referential row. If there is only one ZOTU in the sample, then that will be the only row for that sample.

**Comment by seanmcallister** [comment]
This is still an issue!

**Comment by mooreryan** [comment]
This commit (5fbfb5ac400305e9961ec653687bebc5ae346d51) should fix the issue.

The release is here: https://github.com/mooreryan/ZetaHunter/releases/tag/v0.0.14

Or `git clone` it.

Let me know if this is how you want it.

![screen shot 2016-09-27 at 2 06 40 pm](https://cloud.githubusercontent.com/assets/3172014/18885907/a5b923be-84bb-11e6-95b0-983b3529d871.png)
