### ISSUE TITLE
"Probably_not_zetas" properly classified, but not written to the outfile

### ISSUE THREAD

**Issue by seanmcallister** [mooreryan/ZetaHunter#30]
Sequences that aren't zetas are properly identified as such, and aren't in the OTU calls files, but they also aren't being written to dangerous seques file "probably_not_zetas".

**Comment by mooreryan** [comment]
Do you have some test files to recreate bug?

**Comment by mooreryan** [comment]
Fixed as of `v0.2.1` (605a0c9f4474f60da7957f8d6d01aaa5f83d0d54).

Okay, so here is what is in the `probably_not_zetas` file now (from the README):

>Seqs that are greater than or equal to 97% identity to an outgroup in
the gold databse in the closed reference OTU calling step are placed
in the `probably_not_zetas` file. Also, a sequence that makes it to
the de novo OTU calling step, but is in an OTU of size 1 and that was
closest to an outgroup in the closed reference OTU calling step (but
less than 97% identity to its outgroup hit) will be in the
`probably_not_zetas` file. Finally, sequences flagged as chimeras will
be in the `probably_not_zetas` file as well as the likely chimera
file.
