### ISSUE TITLE
Errors when parse fasta > 1.9.2 installed in global gemset

### ISSUE THREAD

**Issue by mooreryan** [mooreryan/ZetaHunter#32]
It will mask the lower version in this case.

**Comment by seanmcallister** [comment]
Please make it so that the parse-fasta error says something intelligent like: "Make sure you have parse-fasta 1.9.2 installed". Maybe include some menial instructions for making a gemset, or link it!

**Comment by mooreryan** [comment]
As of this commit 91ae3520396fc992b990e5c7abf19efc75f11816, ZH will try and check if the correct version of `parse_fasta` is installed and if not, it will give an error message. It looks like this:

```
FATAL -- [2017-09-12 23:25:14.951] -- Uninitialized constant: FastaFile. ZetaHunter requires parse_fasta library version >= 1.8, but <= 1.9.1. Do you have version 2 installed? Run this command (without the quotes) to find out: 'gem list | grep parse_fasta'.
```
