### ISSUE TITLE
New folders created on running

### ISSUE THREAD

**Issue by seanmcallister** [mooreryan/ZetaHunter#39]
When assets are in path with illegal characters (i.e. -, space, ', etc), the program recreates the entire path and copies the assets there before running, and doesn't remove it after.

This is also true when using ZetaHunter from a release, since the dash before the version number is an illegal character.

**Comment by mooreryan** [comment]
This release should fix this: https://github.com/mooreryan/ZetaHunter/releases/tag/v0.2.2 (commit 843ec729b8cd41a05c133f1411a2129240ebbe10).

Please reopen this issue if it is still giving you trouble.
